### PR TITLE
Add line suffix

### PR DESCRIPTION
**Pull request by merqlove**
Useful in the case, when we want to add custom behavior together with multiple hosts.

### CODE REVIEW

**Comment by atomic-penguin** [comment]
I'm not clear @merqlove why this is needed.  Does the options resources not already provide this capability?  Does it need changed/enhanced to provide something it doesn't already?

**Comment by merqlove** [comment]
as i remember, it is for case when you need exports with some handful part. Which is non standard (different network or something).

**Comment by ramereth** [comment]
@merqlove since moving to Sous Chefs, this cookbook has been refactored quite a bit. Is this PR still needed?

**Comment by damacus** [comment]
## Closing due to inactivity. 

If this is still an issue please reopen or open another PR. 

Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs

**Pull request closed without merging**
